services:
  stakeholders-service:
    build: ./stakeholders-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=stakeholders-db
    depends_on:
      stakeholders-db:
        condition: service_healthy

  stakeholders-db:
    image: postgres:15
    environment:
      POSTGRES_DB: stakeholders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  blog-mongodb:
    image: mongo:7
    ports:
      - "27018:27017"
    volumes:
      - blog_mongo_data:/data/db

  blog-service:
    build: ./blog-service
    ports:
      - "8082:8082"
    environment:
      MONGODB_URI: mongodb://blog-mongodb:27017/blogdb
    depends_on:
      - blog-mongodb

  follower-neo4j:
    image: neo4j:5-community
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password123
    volumes:
      - follower_neo4j_data:/data
      - follower_neo4j_logs:/logs

  follower-service:
    build: ./follower-service
    ports:
      - "8083:8083"
    environment:
      PORT: 8083
      NEO4J_URL: http://follower-neo4j:7474
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password123
      NEO4J_DATABASE: neo4j
      BLOG_SERVICE_URL: http://blog-service:8082
      JWT_SECRET: super-secret-key-123
    depends_on:
      - follower-neo4j
      - blog-service

  frontend:
    build: ./frontend/tourism-app
    ports:
      - "4200:80"
    depends_on:
      - stakeholders-service
      - blog-service
      - api-gateway

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - stakeholders-service
      - blog-service
      - follower-service

volumes:
  blog_mongo_data:
  follower_neo4j_data:
  follower_neo4j_logs:

networks:
  default:
    name: soa-network