version: '3.8'

services:
  stakeholders-service:
    build: ./stakeholders-service
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=stakeholders-db
    depends_on:
      - stakeholders-db

  stakeholders-db:
    image: postgres:15
    environment:
      POSTGRES_DB: stakeholders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"

  blog-service:
    build: ./blog-service
    ports:
      - "8082:8082"
    environment:
      - MONGO_URI=mongodb://blog-db:27017/blog
    depends_on:
      - blog-db

  blog-db:
    image: mongo:6
    ports:
      - "27017:27017"

networks:
  default:
    name: soa-network